### ISSUE TITLE
Possible to do this to PartyArrows?

### ISSUE THREAD

**Issue by kallesgit** [pajlada/PajMinimapArrow#2]
Hello. I really like this addon but was wondering if it's possible to add this for Party/RaidArrows too? Talking about this one (https://i.gyazo.com/0ecf2f94037e0e634dc8cd390a67b8ae.jpg). Ty in advance.

**Comment by pajlada** [comment]
Theoretically yes, not through quite an easily accessible API though.

The `Minimap:SetBlipTexture` function can be used for this, but that's a bigger texture file that contains things like resource nodes, question completion icons etc.

**Comment by kallesgit** [comment]
Thank you for answering. Are you saying it's impossible because it's not viable to distinguish between party arrows and for instance nodes etc? Or would it in theory be possible, but hard?

**Comment by pajlada** [comment]
It would be possible in theory, but difficult because I'm not good with BLP tools

Essentially, the data file looks like this: https://static.wikia.nocookie.net/wowpedia/images/0/0e/OBJECTICONS.png/revision/latest?cb=20210115024544 and we'd want to modify a single one of them (the party icon). Scaling will be more difficult (but still doable).

**Comment by pajlada** [comment]
I'll go ahead and test the feasibility of this now

**Comment by pajlada** [comment]
@Dramatized I have found a way to get this working, and to my surprise party members and raid members actually use different textures, meaning I will want to use this myself too.

Current experimentations I'm doing now is to keep the party icon the same, but make raid members transparent.

Most likely, I would be distributing the addon with a few different variations and allowing others to submit their versions.

This is what it looks like for me with my tests:
![image](https://user-images.githubusercontent.com/962989/143690903-4af4d9e5-a8bf-43ce-82f3-1ec869676fba.png)
Will make drumming a whole lot easier!

I'll keep you updated in the upcoming days, if you have any suggestions or wishes for how you want the party icon to look, let me know and I'll include those in the first draft of the addon.

**Comment by kallesgit** [comment]
Hey, thanks a lot for looking into this. Speaking from a hunter PvP perspective my main wish regarding this would be to get the party/raid arrows removed since they clutter up the minimap with no obvious benefit. 

I’ve spoken to two friends that I know have tried removing these arrows w/o success too. The less transparent raid (and party members if you ask me) would be a super nice addition to that.

**Comment by pajlada** [comment]
@Dramatized I've published the addon here: https://github.com/pajlada/PajBlip https://www.curseforge.com/wow/addons/pajblip

It should be available in addon managers shortly.

For further requests, feel free to open a new issue in the PajBlip repo!

Available textures can be found here: https://github.com/pajlada/PajBlip#textures and checked in game with the `/pajblip texture` command

**Comment by pajlada** [comment]
I just now realized you mean the arrows around the minimap, not necessarily the "circles" that denote a party or raid members. I'll double check that this can be modified

**Comment by pajlada** [comment]
Turns out changing that arrow is actually not possible through the Blip Texture (which is what I change in the new addon I just released). It might be possible to replace the texture in the Interface/Minimap folder somehow, but after 30 minutes of research I have yet to find which exact texture is being used.

**Comment by kallesgit** [comment]
Ah, I see - damnit. Thank you for trying. Let me know if you were ever to find out a way to do it. I'd help but I literally don't know anything about addons or coding myself.
